<?php
declare(strict_types=1);

namespace Modracx\AdminDevTools\Model;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Exception\LocalizedException;
use Magento\Store\Model\StoreManagerInterface;

/**
 * What url_rewrite says about a path.
 *
 * The 404-on-a-product-that-exists question is almost never "is there a rewrite" — it is
 * "there are three, in the wrong stores, and one of them redirects to another one". So the
 * lookup matches on either side of the row and then follows the chain.
 */
class RewriteLookup
{
    private const TABLE = 'url_rewrite';

    private const LIMIT = 50;

    /** How far a redirect chain is followed before it is called a loop. */
    private const MAX_HOPS = 10;

    public function __construct(
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    /**
     * @return array{
     *     path: string,
     *     rows: array<int, array{request_path: string, target_path: string, redirect_type: int, store: string, entity_type: string, entity_id: int, description: ?string, is_autogenerated: bool}>,
     *     chain: array<int, array{from: string, to: string, redirect_type: int, store: string}>,
     *     loop: bool
     * }
     * @throws LocalizedException
     */
    public function lookup(string $path): array
    {
        $path = ltrim(trim($path), '/');

        if ($path === '') {
            throw new LocalizedException(__('Enter a request path, such as my-product.html.'));
        }

        // A pasted URL is what a developer actually has in hand — take the path out of it
        // rather than making them edit it first.
        if (preg_match('~^https?://~i', $path)) {
            $path = ltrim((string) parse_url($path, PHP_URL_PATH), '/');
        }

        $rows = $this->fetch(['request_path = ?' => $path, 'target_path = ?' => $path], true);

        return [
            'path'  => $path,
            'rows'  => $rows,
            'chain' => $this->chain($path),
            'loop'  => $this->isLoop($path),
        ];
    }

    /**
     * Follow request_path → target_path for as long as each target is itself a rewrite.
     *
     * @return array<int, array{from: string, to: string, redirect_type: int, store: string}>
     */
    private function chain(string $path): array
    {
        $chain   = [];
        $current = $path;
        $seen    = [$path => true];

        for ($hop = 0; $hop < self::MAX_HOPS; $hop++) {
            $next = $this->fetch(['request_path = ?' => $current], false);
            if ($next === []) {
                break;
            }

            $row     = $next[0];
            $chain[] = [
                'from'          => $row['request_path'],
                'to'            => $row['target_path'],
                'redirect_type' => $row['redirect_type'],
                'store'         => $row['store'],
            ];

            $current = $row['target_path'];
            if (isset($seen[$current])) {
                break;
            }
            $seen[$current] = true;
        }

        return $chain;
    }

    private function isLoop(string $path): bool
    {
        $seen    = [];
        $current = $path;

        for ($hop = 0; $hop < self::MAX_HOPS; $hop++) {
            if (isset($seen[$current])) {
                return true;
            }
            $seen[$current] = true;

            $next = $this->fetch(['request_path = ?' => $current], false);
            if ($next === [] || $next[0]['target_path'] === $current) {
                return false;
            }

            $current = $next[0]['target_path'];
        }

        return true;
    }

    /**
     * @param  array<string, string> $conditions  fragment => bind value
     * @return array<int, array<string, mixed>>
     */
    private function fetch(array $conditions, bool $anyOf): array
    {
        $connection = $this->resource->getConnection();
        $select     = $connection->select()
            ->from($this->resource->getTableName(self::TABLE))
            ->limit(self::LIMIT)
            ->order(['store_id ASC', 'url_rewrite_id ASC']);

        if ($anyOf) {
            $parts = [];
            foreach ($conditions as $fragment => $value) {
                $parts[] = $connection->quoteInto($fragment, $value);
            }
            $select->where('(' . implode(') OR (', $parts) . ')');
        } else {
            foreach ($conditions as $fragment => $value) {
                $select->where($fragment, $value);
            }
        }

        $rows = [];
        foreach ($connection->fetchAll($select) as $row) {
            $rows[] = [
                'request_path'     => (string) $row['request_path'],
                'target_path'      => (string) $row['target_path'],
                'redirect_type'    => (int) $row['redirect_type'],
                'store'            => $this->storeLabel((int) $row['store_id']),
                'entity_type'      => (string) $row['entity_type'],
                'entity_id'        => (int) $row['entity_id'],
                'description'      => $row['description'] !== null ? (string) $row['description'] : null,
                'is_autogenerated' => (bool) $row['is_autogenerated'],
            ];
        }

        return $rows;
    }

    private function storeLabel(int $storeId): string
    {
        try {
            $store = $this->storeManager->getStore($storeId);

            return sprintf('%s (#%d)', $store->getCode(), $storeId);
        } catch (\Exception $e) {
            // A rewrite can outlive the store view it was created for.
            return (string) __('deleted store #%1', $storeId);
        }
    }
}
